#!/bin/sh
touch ./clearpath/husky/CATKIN_IGNORE
touch ./clearpath/husky/husky_gazebo/CATKIN_IGNORE
touch ./clearpath/moose_simulator/CATKIN_IGNORE
touch ./clearpath/warthog_simulator/CATKIN_IGNORE
touch ./greenzie/boustrophedon_planner/CATKIN_IGNORE
touch ./lucasw/dynamic_reconfigure_tools/rviz_dr_single/CATKIN_IGNORE
touch ./lucasw/screengrab_ros/screen_grab_ros2/CATKIN_IGNORE
touch ./lucasw/simple_sim_ros/diffbot_control/CATKIN_IGNORE
touch ./other/anybotics/elevation_mapping/CATKIN_IGNORE
touch ./other/catkin_virtualenv/test_catkin_virtualenv/CATKIN_IGNORE
touch ./other/depthai-ros-examples/CATKIN_IGNORE
touch ./other/fiducials/aruco_detect/CATKIN_IGNORE
touch ./other/fiducials/aruco_gazebo/CATKIN_IGNORE
touch ./other/fiducials/fiducial_slam/CATKIN_IGNORE
touch ./other/jsk_recognition/imagesift/CATKIN_IGNORE
touch ./other/jsk_recognition/jsk_libfreenect2/CATKIN_IGNORE
touch ./other/jsk_recognition/jsk_pcl_ros/CATKIN_IGNORE
touch ./other/jsk_recognition/jsk_pcl_ros_utils/CATKIN_IGNORE
touch ./other/jsk_recognition/jsk_perception/CATKIN_IGNORE
touch ./other/jsk_recognition/sound_classification/CATKIN_IGNORE
touch ./other/jsk_roseus/CATKIN_IGNORE
touch ./other/jsk_roseus/roseus_msgs/CATKIN_IGNORE
touch ./other/mavros/libmavconn/CATKIN_IGNORE
touch ./other/mavros/mavros/CATKIN_IGNORE
touch ./other/mavros/mavros_extras/CATKIN_IGNORE
touch ./other/mavros/test_mavros/CATKIN_IGNORE
touch ./other/openni2_camera/CATKIN_IGNORE
touch ./other/people/face_detector/CATKIN_IGNORE
touch ./other/people/leg_detector/CATKIN_IGNORE
touch ./other/pid/CATKIN_IGNORE
touch ./ros/gazebo_ros_demos/CATKIN_IGNORE
touch ./ros/gazebo_ros_pkgs/CATKIN_IGNORE
touch ./ros/grid_map/grid_map_demos/CATKIN_IGNORE
touch ./ros/grid_map/grid_map_filters/CATKIN_IGNORE
touch ./ros/joystick_drivers/ps3joy/CATKIN_IGNORE
touch ./ros/joystick_drivers/wiimote/CATKIN_IGNORE
