name: Ubuntu 20.04 Noetic ROS build from source

on:
  push:
  workflow_dispatch:

jobs:
  ubuntu2004:
    runs-on: ubuntu-20.04
    # env:
    steps:
      - name: git clone git@github.com:lucasw/ros_from_src
        uses: actions/checkout@v2
        with:
          path: ros_from_src
          submodules: recursive

      - name: local apt dependencies
        run: |
          mkdir staging
          cd staging
          mkdir -p underlay_ws/src
          cp ../ros_from_src/*sh underlay_ws
          sudo underlay_ws/dependencies.sh

      - name: local git dependencies
        run: |
          cd staging
          cp ../ros_from_src/*yaml underlay_ws/src
          sed -i 's/git@github.com:/https:\/\/github.com\//' underlay_ws/src/underlay_repos.yaml
          # override rosconsole in 20.04 for log4cxx compatibility
          underlay_ws/git_clone.sh

      - name: local build
        run: |
          cd staging
          underlay_ws/build.sh

      - name: local catkin build
        run: |
          cd staging
          underlay_ws/catkin.sh
